name: Saludo usando secretos y variables
run-name: ¡Estoy aprendiendo a usar secretos y var!
on:
  workflow_dispatch
env:
  DIA_DE_SEMANA: Jueves
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: Holiii!!!
    steps:
      - name: Saludar
        run: echo "$SALUDO, ${{vars.NOMBRE}}. Hoy es ${{env.DIA_DE_SEMANA}}! y ni sabes esta es tu clave ${{secrets.AWS_PASS}} "
