name: Triggers
run-name: ¡Estoy aprendiendo a usar diferentes Triggers!
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.go'
  issues:
    types:
      - labeled
  workflow_dispatch:
    inputs:
      lenguaje_favorito:
        description: 'Lenguaje favorito'
        default: Go
        required: true
        type: choice
        options:
        - Python
        - Java
        - Go
      nombre:
        description: 'Iván'
        required: true
        default: IR
        type: string
  schedule:
    - cron:  '15 19 * * *'
jobs:
  hola-mundo-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Definir nombre
        run: echo "USERNAME=${{ inputs.nombre }}" >> $GITHUB_ENV
      - name: Definir lenguaje
        run: echo "LANGUAGE=${{ inputs.lenguaje_favorito }}" >> $GITHUB_ENV
      
  hola-mundo:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24' # Versión estable 

      - name: Ejecutar programa
        # Usamos el path relativo al directorio raiz del repo
        run: go run src/main.go
